#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Symlink every `*.md` in <src> into <dest>.
#
# `_`-prefixed files are shared reference fragments cited by other files, not
# commands or agents of their own, so they are skipped everywhere — previously
# only the commands loops did this, and the agents loops would have installed a
# fragment as an agent the moment one appeared.
link_dir() {
  local src="$1"
  local dest="$2"
  local label="$3"

  mkdir -p "$dest"
  echo ""
  echo "Installing $label..."

  for file in "$src"/*.md; do
    [ -f "$file" ] || continue
    local name
    name=$(basename "$file")

    case "$name" in
      _*) continue ;;
    esac

    local target="$dest/$name"

    if [ -L "$target" ]; then
      rm "$target"
    elif [ -f "$target" ]; then
      # Never clobber an existing backup: a second real file in this slot would
      # otherwise silently overwrite the first one we saved.
      local backup="$target.bak"
      local n=1
      while [ -e "$backup" ]; do
        backup="$target.bak.$n"
        n=$((n + 1))
      done
      echo "  Backing up existing $name -> $(basename "$backup")"
      mv "$target" "$backup"
    fi

    ln -s "$file" "$target"
    echo "  Linked $name"
  done
}

link_dir "$SCRIPT_DIR/commands" "$HOME/.claude/commands" "commands"
link_dir "$SCRIPT_DIR/agents" "$HOME/.claude/agents" "agents"

# Create .env from example if not present (project-level)
if [ ! -f "$SCRIPT_DIR/.env" ] && [ -f "$SCRIPT_DIR/.env.example" ]; then
  cp "$SCRIPT_DIR/.env.example" "$SCRIPT_DIR/.env"
  echo "  Created .env from template — fill in your credentials"
fi

# Create ~/.claude/.env for machine-level config if not present
MACHINE_ENV="$HOME/.claude/.env"
if [ ! -f "$MACHINE_ENV" ]; then
  cat > "$MACHINE_ENV" <<'EOF'
# Machine-level config (shared across all projects using jay-claude-plugins)
# DEV_ROOT=/path/to/your/dev/directory
# SLACK_WEBHOOK_URL=
EOF
  echo "  Created $MACHINE_ENV — set DEV_ROOT to your dev directory"
fi

# Install CLI tools
CLI_DIR="$SCRIPT_DIR/cli"
if [ -d "$CLI_DIR" ]; then
  echo ""
  echo "Installing CLI tools..."
  (cd "$CLI_DIR" && npm install --silent)
  echo "  Dependencies installed"

  # Generate standalone wrappers in ~/.local/bin that invoke a hardcoded node
  # binary. This bypasses asdf shims entirely, so the CLIs keep working inside
  # repos with a different .tool-versions and survive `asdf reshim`.
  # ~/.local/bin must be on PATH ahead of ~/.asdf/shims for the wrappers to win.
  WRAPPER_DIR="$HOME/.local/bin"
  # Resolve to the actual node binary via process.execPath. The `node` in PATH is
  # often an asdf shim (a bash script, not a symlink) — embedding the shim in our
  # wrapper would defeat the purpose. process.execPath always points at the real
  # binary regardless of how node was invoked.
  NODE_BIN="$(node -e 'console.log(process.execPath)' 2>/dev/null)"

  if [ -z "$NODE_BIN" ] || [ ! -x "$NODE_BIN" ]; then
    echo "  Warning: could not resolve a node binary — skipping wrapper generation."
    echo "  Run the CLIs directly with: node $CLI_DIR/bin/<name>.js"
  else
    mkdir -p "$WRAPPER_DIR"
    BINS="$("$NODE_BIN" -e "const p=require('$CLI_DIR/package.json');console.log(Object.keys(p.bin||{}).join(' '))" 2>/dev/null || echo "")"
    generated=0
    for cmd in $BINS; do
      script="$CLI_DIR/bin/$cmd.js"
      [ -f "$script" ] || continue
      wrapper="$WRAPPER_DIR/$cmd"
      cat > "$wrapper" <<EOF
#!/bin/bash
# Generated by jay-claude-plugins/install.sh — bypasses asdf shims to avoid
# version-prompt churn when invoked from repos with a different .tool-versions.
exec $NODE_BIN $script "\$@"
EOF
      chmod +x "$wrapper"
      generated=$((generated + 1))
    done
    if [ "$generated" -gt 0 ]; then
      echo "  Generated $generated CLI wrapper(s) in $WRAPPER_DIR (node: $NODE_BIN)"
      case ":$PATH:" in
        *":$WRAPPER_DIR:"*) ;;
        *) echo "  Warning: $WRAPPER_DIR is not on PATH — add it ahead of ~/.asdf/shims in your shell rc" ;;
      esac
    fi
  fi
fi

# Install into opencode, if opencode is present.
#
# Ordered after the CLI install for two reasons: the sync is itself one of those
# CLIs, and `set -e` means a failure here would otherwise abort the parts that
# already worked.
#
# opencode gets *generated* files rather than symlinks. One file cannot satisfy
# both dialects — `allowed-tools` is not an opencode field, and opencode routes
# unknown frontmatter to the provider as model options while defaulting its
# permissions to *allow*, so a shared file silently hands the read-only reviewers
# write access. Generating costs nothing here because opencode loads agents and
# commands at config time and needs a restart to see a change either way.
OPENCODE_SYNCED=0
if command -v opencode >/dev/null 2>&1 || [ -d "$HOME/.config/opencode" ]; then
  if [ -f "$SCRIPT_DIR/cli/bin/sync-opencode.js" ] && [ -n "$NODE_BIN" ]; then
    echo ""
    echo "Installing opencode agents and commands (generated)..."
    "$NODE_BIN" "$SCRIPT_DIR/cli/bin/sync-opencode.js" || true
    OPENCODE_SYNCED=1
  fi
fi

echo ""
echo "Done. Commands available:"
echo "  /ticket-work       - Run tickets end-to-end (single or queue mode)"
echo "  /orchestrate       - Project-level coordinator across all active stacks"
echo "  /triage-tickets    - One triage pass: auto-promote + detect stagnant tickets"
echo "  /cleanup           - Post-merge teardown (auto-detects phase-1 vs terminal)"
echo "  /cleanup-main      - Explicit terminal cleanup (PR merged to main)"
echo "  /cleanup-feature   - Explicit phase-1 cleanup (PR merged to Epic feature branch)"
echo "  /promote-to-main   - Promote a stacked ticket to main"
echo "  /stack-rebase      - Rebase a stacked PR chain"
echo "  /rebase-on-main    - Rebase the current feature branch onto origin/main"
echo "  /finalize          - Final pre-merge pass on a PR"
echo "  /prune             - Abandon a ticket: revert merge, close PR, cancel Jira"
echo "  /rework            - Reset a ticket and restart the lifecycle from scratch"
echo "  /refresh-research  - Re-run the per-ticket research drift check"
echo "  /fix-drift         - Detect and fix drift between AC and the implementation"
echo "  /ears-requirements - EARS requirements ideation"
echo "  /jay-pr-review     - Generate a PR review plan for the current branch"
echo "  /build-sliced      - Build a feature as dependency-ordered commit slices"
echo "  /review-slices     - Review a sliced-build stack, slice-tagged findings"
echo ""
echo "Agents available:"
echo "  @planner           - Decompose Confluence docs into Gherkin-based Jira backlog"
echo "  @feature-planner   - Decompose a TDD sliced by feature, not by PR size"
echo "  @refactor          - CRAP/DRY analysis and refactoring implementation"
echo "  @diff-critic       - Read-only branch review: correctness, contracts, test gaps"
echo "  @diff-security     - Read-only branch review: secrets, injection, auth, PII"
echo "  @tdd-builder       - Draft a planner-ready TDD from a Jira PRD"
echo "  @condensor         - Rewrite a verbose doc as a shorter version of itself"
echo "  @condense-verified - Condense, then verify against the source and patch defects"
echo ""
echo "CLI tools:"
echo "  ticket-status      - View/manage ticket stacks (run directly in terminal)"
echo "  sync-opencode      - Regenerate the opencode copies after editing an agent/command"
echo ""
echo "Next steps:"
echo "  1. Edit .env — set JIRA_EMAIL, JIRA_API_TOKEN, JIRA_DOMAIN"
echo "  2. Edit ~/.claude/.env — set DEV_ROOT to your dev directory"
if [ "$OPENCODE_SYNCED" = "1" ]; then
  echo "  3. Restart opencode to pick up the generated agents and commands"
  echo ""
  echo 'opencode edit loop: edit the file here -> sync-opencode -> restart opencode.'
  echo 'Agent and command files are config-time in opencode, so a restart was always'
  echo 'required; `sync-opencode --check` exits 2 when the copies are stale.'
fi
