#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
COMMANDS_DIR="$HOME/.claude/commands"

mkdir -p "$COMMANDS_DIR"

echo "Installing commands..."

for cmd in "$SCRIPT_DIR"/commands/*.md; do
  name=$(basename "$cmd")

  # `_`-prefixed files are shared reference fragments cited by other commands,
  # not slash commands of their own. Skip them.
  case "$name" in
    _*) continue ;;
  esac

  target="$COMMANDS_DIR/$name"

  if [ -L "$target" ]; then
    rm "$target"
  elif [ -f "$target" ]; then
    echo "  Backing up existing $name -> $name.bak"
    mv "$target" "$target.bak"
  fi

  ln -s "$cmd" "$target"
  echo "  Linked $name"
done

# Install agents
AGENTS_DIR="$HOME/.claude/agents"
mkdir -p "$AGENTS_DIR"

echo ""
echo "Installing agents..."

for agent in "$SCRIPT_DIR"/agents/*.md; do
  [ -f "$agent" ] || continue
  name=$(basename "$agent")
  target="$AGENTS_DIR/$name"

  if [ -L "$target" ]; then
    rm "$target"
  elif [ -f "$target" ]; then
    echo "  Backing up existing $name -> $name.bak"
    mv "$target" "$target.bak"
  fi

  ln -s "$agent" "$target"
  echo "  Linked $name"
done

# Create .env from example if not present (project-level)
if [ ! -f "$SCRIPT_DIR/.env" ] && [ -f "$SCRIPT_DIR/.env.example" ]; then
  cp "$SCRIPT_DIR/.env.example" "$SCRIPT_DIR/.env"
  echo "  Created .env from template — fill in your credentials"
fi

# Create ~/.claude/.env for machine-level config if not present
MACHINE_ENV="$HOME/.claude/.env"
if [ ! -f "$MACHINE_ENV" ]; then
  cat > "$MACHINE_ENV" <<'EOF'
# Machine-level config (shared across all projects using jay-claude-plugins)
# DEV_ROOT=/path/to/your/dev/directory
# SLACK_WEBHOOK_URL=
EOF
  echo "  Created $MACHINE_ENV — set DEV_ROOT to your dev directory"
fi

# Install CLI tools
CLI_DIR="$SCRIPT_DIR/cli"
if [ -d "$CLI_DIR" ]; then
  echo ""
  echo "Installing CLI tools..."
  (cd "$CLI_DIR" && npm install --silent)
  echo "  Dependencies installed"

  # Generate standalone wrappers in ~/.local/bin that invoke a hardcoded node
  # binary. This bypasses asdf shims entirely, so the CLIs keep working inside
  # repos with a different .tool-versions and survive `asdf reshim`.
  # ~/.local/bin must be on PATH ahead of ~/.asdf/shims for the wrappers to win.
  WRAPPER_DIR="$HOME/.local/bin"
  # Resolve to the actual node binary via process.execPath. The `node` in PATH is
  # often an asdf shim (a bash script, not a symlink) — embedding the shim in our
  # wrapper would defeat the purpose. process.execPath always points at the real
  # binary regardless of how node was invoked.
  NODE_BIN="$(node -e 'console.log(process.execPath)' 2>/dev/null)"

  if [ -z "$NODE_BIN" ] || [ ! -x "$NODE_BIN" ]; then
    echo "  Warning: could not resolve a node binary — skipping wrapper generation."
    echo "  Run the CLIs directly with: node $CLI_DIR/bin/<name>.js"
  else
    mkdir -p "$WRAPPER_DIR"
    BINS="$("$NODE_BIN" -e "const p=require('$CLI_DIR/package.json');console.log(Object.keys(p.bin||{}).join(' '))" 2>/dev/null || echo "")"
    generated=0
    for cmd in $BINS; do
      script="$CLI_DIR/bin/$cmd.js"
      [ -f "$script" ] || continue
      wrapper="$WRAPPER_DIR/$cmd"
      cat > "$wrapper" <<EOF
#!/bin/bash
# Generated by jay-claude-plugins/install.sh — bypasses asdf shims to avoid
# version-prompt churn when invoked from repos with a different .tool-versions.
exec $NODE_BIN $script "\$@"
EOF
      chmod +x "$wrapper"
      generated=$((generated + 1))
    done
    if [ "$generated" -gt 0 ]; then
      echo "  Generated $generated CLI wrapper(s) in $WRAPPER_DIR (node: $NODE_BIN)"
      case ":$PATH:" in
        *":$WRAPPER_DIR:"*) ;;
        *) echo "  Warning: $WRAPPER_DIR is not on PATH — add it ahead of ~/.asdf/shims in your shell rc" ;;
      esac
    fi
  fi
fi

echo ""
echo "Done. Commands available:"
echo "  /ticket-work       - Run tickets end-to-end (single or queue mode)"
echo "  /orchestrate       - Project-level coordinator across all active stacks"
echo "  /triage-tickets    - One triage pass: auto-promote + detect stagnant tickets"
echo "  /cleanup           - Post-merge teardown (auto-detects phase-1 vs terminal)"
echo "  /cleanup-main      - Explicit terminal cleanup (PR merged to main)"
echo "  /cleanup-feature   - Explicit phase-1 cleanup (PR merged to Epic feature branch)"
echo "  /promote-to-main   - Promote a stacked ticket to main"
echo "  /stack-rebase      - Rebase a stacked PR chain"
echo "  /rebase-on-main    - Rebase the current feature branch onto origin/main"
echo "  /finalize          - Final pre-merge pass on a PR"
echo "  /prune             - Abandon a ticket: revert merge, close PR, cancel Jira"
echo "  /rework            - Reset a ticket and restart the lifecycle from scratch"
echo "  /refresh-research  - Re-run the per-ticket research drift check"
echo "  /fix-drift         - Detect and fix drift between AC and the implementation"
echo "  /ears-requirements - EARS requirements ideation"
echo "  /jay-pr-review     - Generate a PR review plan (used by /ticket-work S4.5)"
echo ""
echo "Agents available:"
echo "  @planner           - Decompose Confluence docs into Gherkin-based Jira backlog"
echo "  @refactor          - CRAP/DRY analysis and refactoring implementation"
echo ""
echo "CLI tools:"
echo "  ticket-status      - View/manage ticket stacks (run directly in terminal)"
echo ""
echo "Next steps:"
echo "  1. Edit .env — set JIRA_EMAIL, JIRA_API_TOKEN, JIRA_DOMAIN"
echo "  2. Edit ~/.claude/.env — set DEV_ROOT to your dev directory"
